/*
 * gen_charset.cpp -- Build-time tool that reads glyph PNGs and emits a
 * precomputed charset table as a .cpp file.
 *
 * Usage: gen_charset <font_name> <font_dir> <output.cpp>
 *
 * Errors out on encoding collisions so they're caught at build time,
 * not silently swallowed at runtime.
 *
 * The encoding algorithm is intentionally duplicated here (not linked
 * from paplease-core) so this tool has no runtime dependency on the
 * main library.  Keep it in sync with core/ocr/ocr.cpp.
 */

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <unordered_map>
#include <vector>

#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

using u8  = std::uint8_t;
using u64 = std::uint64_t;

namespace fs = std::filesystem;

// ---- encoding (mirrors core/ocr/ocr.cpp) ----

static cv::Mat downscale_image(const cv::Mat &image)
{
	cv::Mat result;
	cv::resize(image, result,
		   cv::Size((int)((float)image.cols * 0.5f),
			    (int)((float)image.rows * 0.5f)),
		   0, 0, cv::INTER_NEAREST);
	return result;
}

static u64 encode_character_bits(const cv::Mat &character)
{
	cv::Mat ch;
	if (character.rows / 2 >= 1 && character.cols / 2 >= 1)
		ch = downscale_image(character);
	else
		ch = character;

	ch = (ch & 1) ^ 1;

	if (ch.rows * ch.cols >= 64)
		return 0;

	u64 num = 0;
	for (int i = 0; i < ch.rows; i++)
		for (int j = 0; j < ch.cols; j++)
			num = (num << 1) | ch.at<u8>(i, j);
	return num;
}

// ---- filename → character mapping (mirrors PackFont.cmake) ----

static bool filename_to_char(const std::string &stem, char &out)
{
	if (stem == "QUESTION_MARK") { out = '?'; return true; }
	if (stem.size() == 1)        { out = stem[0]; return true; }
	return false;
}

static std::string escape_char(char ch)
{
	if (ch == '\'') return "\\'";
	if (ch == '\\') return "\\\\";
	return std::string(1, ch);
}

// ---- main ----

int main(int argc, char *argv[])
{
	if (argc != 4) {
		fprintf(stderr, "usage: gen_charset <font_name> <font_dir> <output.cpp>\n");
		return 1;
	}

	const char *font_name  = argv[1];
	const char *font_dir   = argv[2];
	const char *output_path = argv[3];

	if (!fs::is_directory(font_dir)) {
		fprintf(stderr, "error: %s is not a directory\n", font_dir);
		return 1;
	}

	// Collect all glyph PNGs, sorted for deterministic output
	std::vector<fs::path> png_files;
	for (const auto &entry : fs::recursive_directory_iterator(font_dir))
		if (entry.is_regular_file() && entry.path().extension() == ".png")
			png_files.push_back(entry.path());
	std::sort(png_files.begin(), png_files.end());

	struct glyph {
		char ch;
		u64 encoding;
		std::string source_path;
	};

	std::vector<glyph> glyphs;
	std::unordered_map<u64, glyph> seen;
	int collisions = 0;

	for (const auto &path : png_files) {
		std::string stem = path.stem().string();
		char ch;
		if (!filename_to_char(stem, ch))
			continue;

		cv::Mat img = cv::imread(path.string(), cv::IMREAD_GRAYSCALE);
		if (img.empty()) {
			fprintf(stderr, "warning: failed to read %s\n",
				path.c_str());
			continue;
		}

		u64 enc = encode_character_bits(img);
		if (enc == 0) {
			fprintf(stderr, "warning: %s ('%c') encodes to 0 "
				"(image %dx%d too large)\n",
				path.c_str(), ch, img.cols, img.rows);
			continue;
		}

		auto it = seen.find(enc);
		if (it != seen.end()) {
			/*
			 * Collision: two glyphs produce the same encoding.
			 * Keep the first one (sorted order: digits before
			 * lowercase before uppercase), warn about the
			 * duplicate.
			 */
			fprintf(stderr,
				"warning: '%c' (%s) collides with '%c' (%s) "
				"at 0x%llx -- keeping '%c'\n",
				ch, path.c_str(), it->second.ch,
				it->second.source_path.c_str(),
				(unsigned long long)enc, it->second.ch);
			collisions++;
			continue;
		}

		seen[enc] = { ch, enc, path.string() };
		glyphs.push_back({ ch, enc, path.string() });
	}

	// Write output .cpp
	FILE *out = fopen(output_path, "w");
	if (!out) {
		fprintf(stderr, "error: cannot open %s for writing\n",
			output_path);
		return 1;
	}

	fprintf(out, "// AUTO-GENERATED by gen_charset -- do not edit\n");
	fprintf(out, "#include \"ocr/charset_table.h\"\n\n");
	fprintf(out, "static const charset_entry %s_entries[] = {\n", font_name);
	for (const auto &g : glyphs)
		fprintf(out, "\t{ '%s', 0x%llxull },\n",
			escape_char(g.ch).c_str(),
			(unsigned long long)g.encoding);
	fprintf(out, "};\n\n");
	fprintf(out, "const charset_table charset_%s = {\n", font_name);
	fprintf(out, "\t%s_entries,\n", font_name);
	fprintf(out, "\t%zu,\n", glyphs.size());
	fprintf(out, "};\n");

	fclose(out);
	fprintf(stderr, "gen_charset: %s -- %zu glyphs",
		font_name, glyphs.size());
	if (collisions > 0)
		fprintf(stderr, " (%d collision%s resolved)",
			collisions, collisions == 1 ? "" : "s");
	fprintf(stderr, "\n");
	return 0;
}
